// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnJbBxbaiaP3czFWdpev07Y-Rm9jG0Gq0',
    appId: '1:544071134717:web:5c390856be8e7d1b8fbd94',
    messagingSenderId: '544071134717',
    projectId: 'saw-s-weather-app',
    authDomain: 'saw-s-weather-app.firebaseapp.com',
    storageBucket: 'saw-s-weather-app.appspot.com',
    measurementId: 'G-SP8XS34MBV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxrE2ggt1sPZfTYoGtxD1Mu_AAjkK5WSw',
    appId: '1:544071134717:android:32486ba06a22075e8fbd94',
    messagingSenderId: '544071134717',
    projectId: 'saw-s-weather-app',
    storageBucket: 'saw-s-weather-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBbRPfj0c1MNMapdrF0QI3XaKXSCVDzh0',
    appId: '1:544071134717:ios:476385583346cc2e8fbd94',
    messagingSenderId: '544071134717',
    projectId: 'saw-s-weather-app',
    storageBucket: 'saw-s-weather-app.appspot.com',
    iosClientId: '544071134717-r4jcgdqh8o5cdbkim7e81ekrj7u0etqt.apps.googleusercontent.com',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBbRPfj0c1MNMapdrF0QI3XaKXSCVDzh0',
    appId: '1:544071134717:ios:476385583346cc2e8fbd94',
    messagingSenderId: '544071134717',
    projectId: 'saw-s-weather-app',
    storageBucket: 'saw-s-weather-app.appspot.com',
    iosClientId: '544071134717-r4jcgdqh8o5cdbkim7e81ekrj7u0etqt.apps.googleusercontent.com',
    iosBundleId: 'com.example.weatherApp',
  );
}
